# Generated by Django 5.1.6 on 2025-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
