# Generated by Django 5.1.6 on 2025-03-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=225, null=True, unique=True),
        ),
    ]
